[package]
name = "tempura"
version = "0.2.2"
edition = "2021"
authors = ["yuma140902"]
description = "Static site generator (SSG) using handlebars and pulldown-cmark"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/yuma140902/tempura"
keywords = ["ssg", "templating", "web", "markdown"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.3.11", features = ["derive"] }
handlebars = "4.3.7"
matter = "0.1.0-alpha4"
once_cell = "1.18.0"
path-absolutize = "3.1.0"
pathdiff = "0.2.1"
pulldown-cmark = "0.9.3"
regex = "1.9.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.22"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
walkdir = "2"
