[package]
name = "tempura"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
frontmatter = "0.4.0"
handlebars = "4.3.5"
pathdiff = "0.2.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
