[package]
name = "tempura"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
handlebars = "4.3.5"
matter = "0.1.0-alpha4"
pathdiff = "0.2.1"
pulldown-cmark = "0.9.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.14"
walkdir = "2"
